[package]
name = "jcl/pathfinding-ting"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@1.2.1"
Promise = "evaera/promise@4.0.0"
ParallelJobHandler = "joshuaclarkelua/parallel-job-handler@^*"