[package]
name = "jcl/fastastar"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@2.0.1"
Promise = "evaera/promise@4.0.0"
ParallelJobHandler = "joshuaclarkelua/parallel-job-handler@^*"
Trove = "sleitnick/trove@1.1.0"