[package]
name = "joshuaclarkelua/parallel-job-handler"
description = "A module for running code in parallel."
license = "MIT"
authors = ["JCL"]
version = "0.1.62"


registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
Signal = "sleitnick/signal@1.2.1"
Promise = "evaera/promise@4.0.0"